In [1]:
import pandas as pd
import numpy as np
from pydataset import data

### 1. Copy the code from the lesson to create a dataframe full of student grades.

In [2]:
# student names
students = ['Sally',
            'Jane',
            'Suzie',
            'Billy',
            'Ada',
            'John',
            'Thomas',
            'Marie',
            'Albert',
            'Richard',
            'Isaac',
            'Alan']

# make students a series
pd.Series(students, name='my_students')

# make column variables and fill with random grades between 60 and 100
math_grades = np.random.randint(
    low=60, high=100, size=len(students))

english_grades = np.random.randint(
    low=60, high=100, size=len(students))

reading_grades = np.random.randint(
    low=60, high=100, size=len(students))

# Create dictionary for DataFrame contents
df_dict = {'name': students,
               'math': math_grades,
               'english': english_grades,
               'reading': reading_grades}

# Create DataFrame with dictionary
df = pd.DataFrame(df_dict)

In [3]:
# a. Create a column named passing_english that indicates whether each student has a passing grade in english.
df['passing_english'] = df.english > 70
df

# b. Sort the english grades by the passing_english column. How are duplicates handled?
df.sort_values('passing_english', ascending=True)

# c. Sort the english grades first by passing_english and then by student name. 
# All the students that are failing english should be first, 
# and within the students that are failing english they should be ordered alphabetically. 
# The same should be true for the students passing english. 
# (Hint: you can pass a list to the .sort_values method)
df.sort_values(['passing_english', 'name'], ascending=[True,True])

# d. Sort the english grades first by passing_english, and then by the actual english grade, 
# similar to how we did in the last step.
df.sort_values(['passing_english', 'english'], ascending=[True,True])

# e. Calculate each students overall grade and add it as a column on the dataframe. 
# The overall grade is the average of the math, english, and reading grades.
df = df.assign(overall_grade=((df.english+df.math+df.reading)/3))

### 2. Load the mpg dataset. Read the documentation for the dataset and use it for the following questions:

In [4]:
# Load mpg dataset
#data('mpg', show_doc=True) # view the documentation for the dataset
mpg = data('mpg') # load the dataset and store it in a variable
mpg

#How many rows and columns are there? ANSWER: 234
mpg.shape

#What are the data types of each column?
mpg.dtypes
    
#Summarize the dataframe with .info and .describe
#print(mpg.info())
#print(mpg.describe())

#Rename the cty column to city.
mpg = mpg.rename(columns={
    'cty':'city'
    })

#Rename the hwy column to highway.
mpg = mpg.rename(columns={
    'hwy':'highway'
    })

#Do any cars have better city mileage than highway mileage? ANSWER: Zero cars have better city mileage.
sum(mpg['city'] > mpg['highway'])

#Create a column named mileage_difference this column should contain the difference 
# between highway and city mileage for each car.
mpg = mpg.assign(mileage_difference=((mpg.highway-mpg.city)))

#Which car (or cars) has the highest mileage difference? ANSWER: Honda Civic & Volkswagen New Beetle
#method 1
mpg.sort_values(['mileage_difference'], ascending=False)
#method 2
mpg[mpg.mileage_difference == mpg.mileage_difference.max()]

#Which compact class car has the lowest highway mileage? The best? 
# ANSWER: Worst - index 220; Best - index 213
mpg.sort_values(
    'highway', ascending=False
)[mpg['class'] == 'compact'].head()

#Create a column named average_mileage that is the mean of the city and highway mileage.
mpg = mpg.assign(
    average_mileage=(mpg.highway+mpg.city)/2)

#Which dodge car has the best average mileage? The worst? ANSWER: Best-index 38; Worst-indexes(55, 70, 60, 66)
mpg.sort_values(
    'average_mileage', ascending=True
)[mpg['manufacturer'] == 'dodge'].head()

/var/folders/kj/13f127m163l12181fcrgh1vm0000gn/T/ipykernel_54579/1238366241.py:41: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  mpg.sort_values(
/var/folders/kj/13f127m163l12181fcrgh1vm0000gn/T/ipykernel_54579/1238366241.py:50: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  mpg.sort_values(

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference,average_mileage
55,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3,10.5
70,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup,3,10.5
60,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,3,10.5
66,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3,10.5
57,dodge,dakota pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,4,13.0

### 3. Load the Mammals dataset. Read the documentation for it, and use the data to answer these questions:

In [18]:
# Load dataset
#data('Mammals', show_doc=True) # view the documentation for the dataset
mammals = data('Mammals')
mammals

#How many rows and columns are there? ANSWER: (107, 4)
mammals.shape

#What are the data types? ANSWER: float64, bool
mammals.dtypes

#Summarize the dataframe with .info and .describe
#ANSWER:
#print(mammals.info())
#print(mammals.describe())


#What is the the weight of the fastest animal? ANSWER: 55
mammals.head()
#method 1
mammals.sort_values('speed', ascending=False).head(1)
#method 2
mammals[mammals.speed == mammals['speed'].max()]['weight'].values[0]

#What is the overal percentage of specials? ANSWER: 9.35
#method 1
mammals['specials'].value_counts()
10/(97+10) * 100
#method 2
round((mammals.specials.sum() / mammals.specials.size) * 100, 2)
#method 3
round((mammals.specials.mean() * 100), 2)

#How many animals are hoppers that are above the median speed? What percentage is this?
speed_mask = mammals.speed > mammals.speed.median()
hopper_mask = mammals.hoppers

mammals[speed_mask & hopper_mask].shape[0]

7